//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace OODataBase_ClassLibrary
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Element0", Namespace="", IsNullable=false)]
    public partial class Laptop : Computer {
        
        private int batteryCapacityField;
        
        private int screenSizeField;
        
        private string resolutionField;
        
        private string keyboardTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int BatteryCapacity {
            get {
                return this.batteryCapacityField;
            }
            set {
                this.batteryCapacityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ScreenSize {
            get {
                return this.screenSizeField;
            }
            set {
                this.screenSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Resolution {
            get {
                return this.resolutionField;
            }
            set {
                this.resolutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KeyboardType {
            get {
                return this.keyboardTypeField;
            }
            set {
                this.keyboardTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Tablet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Desktop))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Laptop))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Computer : Item {
        
        private int rAMField;
        
        private int rOMField;
        
        private string processorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int RAM {
            get {
                return this.rAMField;
            }
            set {
                this.rAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ROM {
            get {
                return this.rOMField;
            }
            set {
                this.rOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Processor {
            get {
                return this.processorField;
            }
            set {
                this.processorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Phone))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Mobile))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Regular))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Smart))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Landline))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Wire))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Wireless))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Appliances))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cooking))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Microwave))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Oven))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cooker))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Machine))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Dishwasher))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DryingMachine))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WashingMachine))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CoolingDevice))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Freezer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Fridge))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AirConditioner))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Computer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Tablet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Desktop))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Laptop))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Item {
        
        private int priceField;
        
        private string brandField;
        
        private int idField;
        
        private int versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Mobile))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Regular))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Smart))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Landline))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Wire))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Wireless))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Phone : Item {
        
        private int speakerVolumeField;
        
        private string microphoneSensitivityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int SpeakerVolume {
            get {
                return this.speakerVolumeField;
            }
            set {
                this.speakerVolumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MicrophoneSensitivity {
            get {
                return this.microphoneSensitivityField;
            }
            set {
                this.microphoneSensitivityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Regular))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Smart))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Mobile : Phone {
        
        private string osField;
        
        private int rAMField;
        
        private int rOMField;
        
        private int screenSizeField;
        
        private string resolutionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OS {
            get {
                return this.osField;
            }
            set {
                this.osField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int RAM {
            get {
                return this.rAMField;
            }
            set {
                this.rAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ROM {
            get {
                return this.rOMField;
            }
            set {
                this.rOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ScreenSize {
            get {
                return this.screenSizeField;
            }
            set {
                this.screenSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Resolution {
            get {
                return this.resolutionField;
            }
            set {
                this.resolutionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Wire))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Wireless))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Landline : Phone {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cooking))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Microwave))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Oven))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cooker))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Machine))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Dishwasher))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DryingMachine))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WashingMachine))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CoolingDevice))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Freezer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Fridge))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AirConditioner))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Appliances : Item {
        
        private int noiseLevelField;
        
        private string energyClassField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NoiseLevel {
            get {
                return this.noiseLevelField;
            }
            set {
                this.noiseLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EnergyClass {
            get {
                return this.energyClassField;
            }
            set {
                this.energyClassField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Microwave))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Oven))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cooker))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Cooking : Appliances {
        
        private int maxTemperatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int MaxTemperature {
            get {
                return this.maxTemperatureField;
            }
            set {
                this.maxTemperatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Dishwasher))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DryingMachine))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WashingMachine))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Machine : Appliances {
        
        private int volumeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Freezer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Fridge))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AirConditioner))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CoolingDevice : Appliances {
        
        private int minCoolingTemperatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int MinCoolingTemperature {
            get {
                return this.minCoolingTemperatureField;
            }
            set {
                this.minCoolingTemperatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Element1", Namespace="", IsNullable=false)]
    public partial class Desktop : Computer {
        
        private string typeField;
        
        private int powerSupplyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int PowerSupply {
            get {
                return this.powerSupplyField;
            }
            set {
                this.powerSupplyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Element2", Namespace="", IsNullable=false)]
    public partial class Tablet : Computer {
        
        private int batteryCapacityField;
        
        private int screenSizeField;
        
        private string resolutionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int BatteryCapacity {
            get {
                return this.batteryCapacityField;
            }
            set {
                this.batteryCapacityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ScreenSize {
            get {
                return this.screenSizeField;
            }
            set {
                this.screenSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Resolution {
            get {
                return this.resolutionField;
            }
            set {
                this.resolutionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Element3", Namespace="", IsNullable=false)]
    public partial class AirConditioner : CoolingDevice {
        
        private int coolingCapacityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CoolingCapacity {
            get {
                return this.coolingCapacityField;
            }
            set {
                this.coolingCapacityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Element4", Namespace="", IsNullable=false)]
    public partial class Fridge : CoolingDevice {
        
        private string typeField;
        
        private int volumeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Element5", Namespace="", IsNullable=false)]
    public partial class Freezer : CoolingDevice {
        
        private int volumeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Element6", Namespace="", IsNullable=false)]
    public partial class WashingMachine : Machine {
        
        private int tubDiameterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TubDiameter {
            get {
                return this.tubDiameterField;
            }
            set {
                this.tubDiameterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Element7", Namespace="", IsNullable=false)]
    public partial class DryingMachine : Machine {
        
        private int tubDiameterField;
        
        private string dryingModeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TubDiameter {
            get {
                return this.tubDiameterField;
            }
            set {
                this.tubDiameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DryingMode {
            get {
                return this.dryingModeField;
            }
            set {
                this.dryingModeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Element8", Namespace="", IsNullable=false)]
    public partial class Dishwasher : Machine {
        
        private int numberOfLevelsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NumberOfLevels {
            get {
                return this.numberOfLevelsField;
            }
            set {
                this.numberOfLevelsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Element9", Namespace="", IsNullable=false)]
    public partial class Cooker : Cooking {
        
        private string panelTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PanelType {
            get {
                return this.panelTypeField;
            }
            set {
                this.panelTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Element10", Namespace="", IsNullable=false)]
    public partial class Oven : Cooking {
        
        private int volumeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Element11", Namespace="", IsNullable=false)]
    public partial class Microwave : Cooking {
        
        private int volumeField;
        
        private string managingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Managing {
            get {
                return this.managingField;
            }
            set {
                this.managingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Element12", Namespace="", IsNullable=false)]
    public partial class Wireless : Landline {
        
        private int batteryCapacityField;
        
        private int rangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int BatteryCapacity {
            get {
                return this.batteryCapacityField;
            }
            set {
                this.batteryCapacityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Element13", Namespace="", IsNullable=false)]
    public partial class Wire : Landline {
        
        private int cableLengthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CableLength {
            get {
                return this.cableLengthField;
            }
            set {
                this.cableLengthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Element14", Namespace="", IsNullable=false)]
    public partial class Smart : Mobile {
        
        private string wiFiTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WiFiType {
            get {
                return this.wiFiTypeField;
            }
            set {
                this.wiFiTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Element15", Namespace="", IsNullable=false)]
    public partial class Regular : Mobile {
    }
}
